### ISSUE TITLE
Programmation 

### ISSUE THREAD

**Issue by walloux1981** [philpownall/ESPHome-Servo-Robot#1]
hello how do you program it, I don't understand all the files, you have to program it via esphome or another way

**Comment by philpownall** [comment]
Yes, you have to program it using esphome.  There is a good getting started section at https://esphome.io/ - once you have installed esphome on your computer, you copy the .yaml file into your device .yaml file, and then "install" (compile and upload the firmware) to your ESP32 device.  Then, it is just a matter of wiring up your SG90 servos and other components to the ESP32 microcontroller, 3D-printing the chassis, and you have a functional servo robot.
